# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes
#-Dfile.encoding=UTF-8
#Application Configuration
jwt:
  secret: "mysupersecretkeythatshouldbe32bytes1234"
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: blog-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: lmedinaencalada@gmail.com
    password: $SPRING_MAIL_PASSWORD
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  h2:
    console:
      enabled: false
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/miublog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: miublog
    password: miublog

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        connection:
          useUnicode: true
          characterEncoding: utf8mb4
          charSet: utf8mb4
logging:
  level:
    root: INFO
    edu.miu.blog.app: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/miu-blog-backend.log
    max-size: 10MB
    max-history: 30
